// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Amazon.SimpleWorkflow.Extensions")]
[assembly: AssemblyProductAttribute("Amazon.SimpleWorkflow.Extensions")]
[assembly: AssemblyDescriptionAttribute("Provides an intuitive API for modelling workflows against SWF")]
[assembly: AssemblyVersionAttribute("1.2.2")]
[assembly: AssemblyFileVersionAttribute("1.2.2")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.2.2";
    }
}
